baseURL = "https://hss24.netlify.app"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "anubis"

[pagination]
  pagerSize = 3

[services.disqus]
  shortname = ""

[params]
name = "Digital Research Alliance of Canada | Alliance de recherche numÃ©rique du Canada"
author = "Digital Research Alliance of Canada | Alliance de recherche numÃ©rique du Canada"
description = "HSS Winter Series 2024 | Ã‰cole hivernale des SHS 2024"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = false
# locale = "en-us"
mathjax = false
googleAnalytics = ""

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional
  
# [[params.social]]
# id = "docs"
# url = "https://gohugo.io/documentation/"

# [[params.social]]
# id = "github"
# url = "https://github.com/mitrichius/hugo-theme-anubis"

[languages.en]
languageName = "English"
title = "HSS Winter Series 2024"
[[menu.main]]
identifier = "id_program"
name = "Program ðŸ•—"
url = "/program/"
weight = 1
[[menu.main]]
identifier = "id_contact"
name = "Contact ðŸ“¬"
url = "/contact/"
weight = 3

[languages.fr]
languageName = "FranÃ§ais"
title = "Ã‰cole hivernale des SHS 2024"
[[languages.fr.menu.main]]
identifier = "id_program"
name = "Programme ðŸ•—"
url = "/program/"
weight = 1
[[languages.fr.menu.main]]
identifier = "id_contact"
name = "Nous joindre ðŸ“¬"
url = "/contact/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup.goldmark.renderer]
unsafe = true
